[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
maxRetries = 3

[[mounts]]
source = "/data"
destination = "/data"

[[services]]
name = "web"
internal_port = 3001
protocol = "http"

[[services.ports]]
port = 3001
handlers = ["http"]

[services.concurrency]
type = "connections"
hard_limit = 250
soft_limit = 200

[[services.scaling]]
min_replicas = 1
max_replicas = 3